YEL-33 [feat] add friend
team-yello/YELLO-Server pull request #21
Opened 2023-07-04 15:23 UTC by hyeonjeongs

### ☘️ Related Issue
* resolves YEL-33 

### ✅ Work description
* 친구 추가하기 완료

### 💡 PR point
* 에러처리는 도메인별로 분기처리한 코드 받고 할 생각입니다! (현재 적용 안함)
* 이미 있는 데이터일때 등록되지 않도록 설정 -> 에러처리 추후 진행 예정

2023-07-05 00:15 UTC, euije approved these changes
고생하셨습니더

2023-07-05 00:15 UTC, euije commented on src/main/java/com/yello/server/domain/friend/entity/FriendRepository.java
> +    Friend findByFollowingAndFollower(@Param("userId") Long userId, @Param("friendId") Long friendId);
Proxy 객체가 아닌 id로 메소드를 구성한 이유가 궁금합니다

2023-07-05 00:15 UTC, euije commented on src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
> +        }
나중에 해당 케이스는 400번대 status를 응답하도록 처리해주어야할 것 같아요 (나중에!!)

2023-07-05 00:18 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/friend/entity/FriendRepository.java
> +    Friend findByFollowingAndFollower(@Param("userId") Long userId, @Param("friendId") Long friendId);
id가 고유한 값이라 query 구성시 사용했습니다

2023-07-05 00:18 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/vote/controller/VoteController.java
> +@RequestMapping("api/v1/vo/te")
엇 제 부분은 아닌데 오타일까요

2023-07-05 00:18 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
> +        }
맞아요 pull 받고 에러 처리 해주려 합니다.

2023-07-05 12:49 UTC, devkwonsehoon requested changes
수고탱탱구리

2023-07-05 12:49 UTC, devkwonsehoon commented on src/main/java/com/yello/server/domain/user/entity/Social.java
> +                .orElseThrow(() -> new IllegalArgumentException(String.format("존재하지 않는 성별입니다.", dbData)));
요거 제 코드 머지해도 사용할 메서드인가요ㅕ??
메세지가 성별로 되어있는 것 같아서 수정이 필요해보입니다.
```suggestion
                .orElseThrow(() -> new IllegalArgumentException(String.format("존재하지 않는 소셜입니다.", dbData)));
```

2023-07-05 12:49 UTC, devkwonsehoon commented on src/main/java/com/yello/server/friend/FriendController.java
> +@Tag(name = "01. Friend")
스웨거에서 01은 Vote가 담당하고 있어서

```suggestion
@Tag(name = "02. Friend")
```

로 고쳐야 할 것 같아요!

2023-07-05 12:49 UTC, devkwonsehoon commented on src/test/java/com/yello/server/friend/FriendControllerTest.java
> +    }
궁금한게 이렇게 Test 돌리면 실제 데이터베이스에 데이터를 적재하는 쿼리가 일어나는건가요? @hyeonjeongs

2023-07-05 13:06 UTC, devkwonsehoon reviewed
하나만 더 추가 ㅎ.

2023-07-05 13:33 UTC, devkwonsehoon reviewed
하나만 더 ㅎ..ㅎ

2023-07-05 16:47 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/user/entity/Social.java
> +                .orElseThrow(() -> new IllegalArgumentException(String.format("존재하지 않는 성별입니다.", dbData)));
넴 enumConverter 때문에 사용했습니다~

2023-07-06 05:59 UTC, devkwonsehoon approved these changes

2023-07-06 05:59 UTC, merged