YEL-26 [feat] 아이디 중복 확인 API
team-yello/YELLO-Server pull request #27
Opened 2023-07-09 02:55 UTC by euije

### ☘️ Related Issue
* resolves 
* yelloId 중복 확인

### ✅ Work description
*
![스크린샷 2023-07-09 오전 11 49 55](https://github.com/team-yello/YELLO-Server/assets/12531340/bfea0e79-889e-4d14-9ed6-e70f810164ea)
![스크린샷 2023-07-09 오전 11 48 15](https://github.com/team-yello/YELLO-Server/assets/12531340/628522fe-d619-48be-82cc-020293e88490)
![스크린샷 2023-07-09 오전 11 44 09](https://github.com/team-yello/YELLO-Server/assets/12531340/ef1591e3-64cd-46a0-a91b-5ff64fc47df2)

### 💡 PR point
*

2023-07-10 07:04 UTC, devkwonsehoon requested changes
( _ _ )

2023-07-10 07:04 UTC, devkwonsehoon commented on src/main/java/com/yello/server/domain/user/controller/AuthController.java
> +        return BaseResponse.success(SuccessCode.YELLOID_VALIDATION_SUCCESS, authService.isYelloIdDuplicated(yelloId));
service 코드를 호출하는 부분을 바로 파라미터 위치에 넣는 것은 한눈에 보기 힘들 수 있어요!
메서드 호출의 인자는 적으면 적을 수록 깔끔한 코드라고 할 수 있는데,
인자 부분에서 뎁쓰가 너무 깊어지는 것 같아요!

`authService.isYelloIdDuplicated(yelloId)` 의 리턴 값을 변수로 받는 것을 추천드림니다.
그리고 저번에 말했던 val을 활용해보아요

2023-07-10 07:04 UTC, devkwonsehoon commented on src/main/java/com/yello/server/domain/user/service/AuthServiceImpl.java
> +
컨벤션 정립을 위해서 요기 중괄호 넣어주시면 감사하겠씁니다

2023-07-12 09:45 UTC, hyeonjeongs approved these changes
수고하셨습니다. 파일만 올리시고 머지하시면 될 것 같아요!

2023-07-12 09:45 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/user/controller/AuthController.java
> +        return BaseResponse.success(SuccessCode.YELLOID_VALIDATION_SUCCESS, authService.isYelloIdDuplicated(yelloId));
swagger도 추가하셔야할 것 같아요!

2023-07-12 09:45 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/user/service/AuthServiceImpl.java
> +
세훈님이 static으로 ErrorCode 선언하는 것을 추천하시는 것 같아서 통일하면 좋을 것 같아요

2023-07-12 12:08 UTC, devkwonsehoon approved these changes

2023-07-12 12:09 UTC, merged