YEL-40 [feat] YELLO 투표하기 시작 가능여부 조회 API 개발
team-yello/YELLO-Server pull request #32
Opened 2023-07-11 07:11 UTC by hyeonjeongs

### ☘️ Related Issue
* resolves YEL-40

### ✅ Work description
* 옐로하기 클릭시 친구 4명 이하인 경우 400 에러
* 40분 지나지 않은 경우 isStart = false 전달

### 💡 PR point
*

2023-07-11 15:55 UTC, devkwonsehoon requested changes
고생티비

2023-07-12 00:38 UTC, euije approved these changes
고생하셨습니다

2023-07-12 00:38 UTC, euije commented on src/main/java/com/yello/server/domain/question/service/YelloVoteServiceImpl.java
> +    }
해당 메소드로 TimeUtil과 같은 파일에서 같이 관리하는게 좋아보여요

2023-07-12 00:38 UTC, euije commented on src/main/java/com/yello/server/domain/question/dto/response/YelloStartResponse.java
> +){
응답 type이 primitive type이 아닌 이유가 있나요??

2023-07-12 06:52 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
> +            throw new FriendException(ErrorCode.LACK_USER_EXCEPTION);
나중에 refactoring 하겠습니다!

2023-07-12 07:04 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/question/controller/YelloVoteController.java
> +@RequestMapping("api/v1/yello")
오케이 수정했습니다!

2023-07-12 07:05 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/question/controller/YelloVoteController.java
> +    @GetMapping("/vote")
넵!

2023-07-12 07:06 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/question/controller/YelloVoteController.java
> +    public BaseResponse<YelloStartResponse> checkYelloStart(
넵!

2023-07-12 07:07 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/question/controller/YelloVoteController.java
> +        return BaseResponse.success(SuccessCode.READ_YELLO_START_SUCCESS, data);
넵 나중에 refactoring 하겠습니다!

2023-07-12 07:08 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/question/service/YelloVoteService.java
> +    YelloStartResponse yelloStartCheck(Long userId);
수정했습니다!

2023-07-12 07:09 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/question/service/YelloVoteServiceImpl.java
> +                .orElseThrow(() -> new UserException(ErrorCode.NOT_FOUND_USER_EXCEPTION));
아아 넵! 나중에 만들 생각이었습니다!!

2023-07-12 07:10 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/question/service/YelloVoteServiceImpl.java
> +        if(friends.size() <4)
넵 알겠습니다!

2023-07-12 07:15 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/question/service/YelloVoteServiceImpl.java
> +        }
알겠습니다!

2023-07-12 07:38 UTC, hyeonjeongs commented on src/main/java/com/yello/server/global/common/util/DataFormatUtil.java
> +
넵 반영하겠습니다!

2023-07-12 07:38 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/question/service/YelloVoteServiceImpl.java
> +    }
넵 반영하겠습니다!

2023-07-12 07:40 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/question/dto/response/YelloStartResponse.java
> +){
null 값을 허용하기 때문에 사용했습니다.

2023-07-12 07:51 UTC, devkwonsehoon approved these changes

2023-07-12 07:51 UTC, merged