YEL 41 [feat] school recommend friend 조회 API
team-yello/YELLO-Server pull request #33
Opened 2023-07-11 09:02 UTC by hyeonjeongs

### ☘️ Related Issue
* resolves YEL-41

### ✅ Work description
* 학교 추천친구 페이지네이션 구현

### 💡 PR point
*

2023-07-11 16:08 UTC, devkwonsehoon requested changes
수고수고수고요

전체적으로 클래스에 @Builder 어노테이션 사용후 하나의 엔티티 인자만 받는 of 메서드를 활용하면
코드가 더 깔끔해질 것 같아요👍

2023-07-11 16:08 UTC, devkwonsehoon commented on src/main/java/com/yello/server/domain/friend/dto/response/RecommendFriendResponse.java
> +                .schoolData(user.getGroup().getSchoolName() +  " " + user.getGroup().getDepartmentName() + " " +user.getGroup().getAdmissionYear()+ "학번")
필드명은 schoolData -> group 어떠신가요?? 
추후에 학교 이외의 그룹이 더 생길 수도 있을 것 같아서요!

그리고, 그룹을 하나의 문자열로 만드는건 School 엔티티에 toString()을 오버라이딩 해둔 것이 있어서
고거 활용하면 될 것 같습니다.

```suggestion
public record RecommendFriendResponse(
        Long id,
        String name,
        String group,
        String profileImage
) {
    public static RecommendFriendResponse of(User user) {
        return RecommendFriendResponse.builder()
                .id(user.getId())
                .name(user.getName())
                .group(user.getGroup().toString())
                ...
```

2023-07-11 16:08 UTC, devkwonsehoon commented on src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
> +                .collect(Collectors.toList());
새로 나온 toList()를 활용하면 코드가 더 깔끔해질 것 같아요!~!

2023-07-11 16:08 UTC, devkwonsehoon commented on src/main/java/com/yello/server/domain/question/dto/response/YelloQuestion.java
> +                .keywordFoot(Objects.isNull(question.getKeywordFoot()) ? null : question.getKeywordFoot())
요 코드의 동작이 이해가 잘 안되는데, 설명해주실 수 있을까요ㅕ!!

2023-07-11 16:08 UTC, devkwonsehoon commented on src/main/java/com/yello/server/domain/question/dto/response/YelloStartResponse.java
> +        Boolean isStart,
나중에 가능/불가능을 떠나 다른 상태값이 들어갈 수도 있다는 생각이 들었는데
그걸 대비해서 VoteStatus 같은 enum으로 처리하는 건 어떠신가요?

2023-07-12 00:47 UTC, euije approved these changes
고생하셨습니다!

2023-07-12 00:47 UTC, euije commented on src/main/java/com/yello/server/global/common/util/PaginationUtil.java
> +    }
Pagable 을 활용한 기능 구현이 인상적입니다

2023-07-12 05:57 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/question/dto/response/YelloQuestion.java
> +                .keywordFoot(Objects.isNull(question.getKeywordFoot()) ? null : question.getKeywordFoot())
NULL 처리하는 코드입니다! 해당 값에 NULL 값이 들어갈 수 있기 때문에, null인 경우는 해당 칼럼에 null을 저장하고 아닌 경우에는 해당 값을 저장합니다!

2023-07-12 06:05 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
> +                .collect(Collectors.toList());
알겠습니다~

2023-07-12 06:05 UTC, hyeonjeongs commented on src/main/java/com/yello/server/global/common/util/PaginationUtil.java
> +    }
감사합니다

2023-07-12 06:08 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/question/service/YelloVoteServiceImpl.java
> +    }
넵 수정하겠습니다~

2023-07-12 06:12 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/question/service/YelloVoteServiceImpl.java
> +                .orElse(Cooldown.builder().user(user).createdAt(null).build());
넵 수정하겠습니다!

2023-07-12 06:14 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/question/entity/Question.java
> +    @OneToMany(mappedBy = "question", cascade = CascadeType.ALL)
DB에 persist하지 않아도 자동으로 반영되기 때문에 사용했습니다!

2023-07-12 06:17 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/question/dto/response/YelloStartResponse.java
> +        Boolean isStart,
어떤 값이 들어갈 수 있을까요?

2023-07-12 06:18 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/friend/controller/FriendController.java
> +    }
오호 카카오 구현시 적용해보겠습니다.

2023-07-12 06:20 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/friend/dto/response/RecommendFriendResponse.java
> +                .schoolData(user.getGroup().getSchoolName() +  " " + user.getGroup().getDepartmentName() + " " +user.getGroup().getAdmissionYear()+ "학번")
오 수정하겠습니다!

2023-07-12 07:51 UTC, devkwonsehoon approved these changes

2023-07-12 08:16 UTC, merged