YEL-187 [feat] token 시간 동적으로 바꾸기
team-yello/YELLO-Server pull request #413
Opened 2024-01-28 19:20 UTC by euije

### ☘️ Related Issue
* resolves 
* token 시간을 동적으로 바꿈
* Redis 삭제

### ✅ Work description
* 

### 💡 PR point
*

2024-01-29 00:49 UTC, hyeonjeongs requested changes
토큰시간 동적으로 바꿀 수 있게해서 요청사항에 대해 빠르게 대응할 수 있을 것 같네요. 수고하셨습니다!

2024-01-29 00:49 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/admin/service/AdminService.java
> +
nullable 처리 repositoryImpl에서 하는 것도 좋아보입니다.

2024-01-29 00:49 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/admin/service/AdminService.java
> +        }
이부분 list에 null로 받아온 경우 `if(list.isEmpty()))` 이전에 서버 에러가 발생하지 않나요???

2024-01-29 00:49 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/authorization/service/AuthManagerImpl.java
> +
이 부분도 값이 없는 경우 excepiton 처리 이전에 서버 에러 발생하는지 확인하면 좋을 것 같습니다

2024-01-29 00:49 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/admin/repository/AdminConfigurationRepositoryImpl.java
> +    }
get(0)으로 0번째 인덱스만 가져올거면 여기서 sort desc로 최신꺼를 가져오는 것으로 해야할 것 같아요.
지금 로직에서는 가장 오래된 값을 가져오는 로직인 것 같습니다.

2024-01-30 03:00 UTC, euije commented on src/main/java/com/yello/server/domain/admin/service/AdminService.java
> +
이거는 getConfigurations -> findConfigurations로 변경해서 Service에서 예외처리하겠습니다
size가 0인 리스트일때의 로직처리를 하기 위해서에요

2024-01-30 03:05 UTC, euije commented on src/main/java/com/yello/server/domain/admin/service/AdminService.java
> +        }
tuple이 없을 경우, list는 size가 0인 `[]`이 반환됩니다.
https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/query/QueryByExampleExecutor.html

2024-01-30 03:05 UTC, euije commented on src/main/java/com/yello/server/domain/authorization/service/AuthManagerImpl.java
> +
위와 동일합니다.

2024-01-30 03:06 UTC, euije commented on src/main/java/com/yello/server/domain/admin/repository/AdminConfigurationRepositoryImpl.java
> +    }
AdminConfiguration은 Date를 상태로 가지지 않습니다

2024-01-30 05:12 UTC, hyeonjeongs approved these changes
수고하셨습니다!! 화이팅

2024-01-30 05:12 UTC, hyeonjeongs commented on src/main/java/com/yello/server/domain/admin/service/AdminService.java
> +        }
아 리스트군요 굿굿!

2024-01-30 05:27 UTC, merged