Feat/yel 14 entity
team-yello/YELLO-Server pull request #9
Opened 2023-06-28 06:55 UTC by hyeonjeongs

### ☘️ Related Issue
* resolves YEL-14

### ✅ Work description
* Entity 개발
* repository 생성

### 💡 PR point
*

2023-06-28 07:28 UTC, euije approved these changes
Record는 완전 데이터 불변 객체라
Setter에 의존하는 JPA의 @entitiy 사용 불가능!!
DTO에만 사용할 것!!

2023-06-28 11:34 UTC, devkwonsehoon requested changes
고생하셨습니다 ~~!_!

2023-06-28 11:34 UTC, devkwonsehoon commented on src/main/java/com/yello/server/entity/cooldown/Cooldown.java
> +@Table(name= "cooldowns")
cooldowns로 따로 네이밍 지은 이유가 궁금함니다

2023-06-28 11:34 UTC, devkwonsehoon commented on src/main/java/com/yello/server/entity/group/School.java
> +    private Long admissionYear;
admissionYear는 입학년도 아니면 18, 19 이런 식의 학번일 것 같아서, Long 보다는 Integer 로 처리하는 것은 어떠하신가요? 메모리도 아낄겸?!

2023-06-28 11:34 UTC, devkwonsehoon commented on src/main/java/com/yello/server/entity/user/User.java
> +    private long point;
요기 point는 왜 primitive type으로 하신지 궁금합니다!!

2023-06-28 11:34 UTC, devkwonsehoon commented on src/main/java/com/yello/server/entity/user/User.java
> +    private long uuid;
uuid는 String으로 가져가야할 것 같습니다!!
근데 이 uuid 값으로 유저에 접근할 일이 꽤 많을 것 같아서 String으로 처리할거면
얘도 레디스 메모리에서 관리하는 게 괜찮을 것 같기도 하네요 얘기해보시져

2023-06-28 11:34 UTC, devkwonsehoon commented on src/main/java/com/yello/server/entity/vote/Vote.java
> +    private Boolean inAnswerHint;
요 네이밍이 살짝 헷갈리는 것 같은데 
중간에 들어간 키워드를 확인했냐 안했냐를 처리하는 거면 
위에 nameHint처럼 keywordHint 로 통일하는 건 어떠신지?

2023-06-29 00:32 UTC, euije commented on src/main/java/com/yello/server/entity/group/School.java
> +    private Long admissionYear;
저도 동의합니다

2023-06-29 00:55 UTC, euije commented on src/main/java/com/yello/server/entity/vote/Vote.java
> +    private Boolean inAnswerHint;
`nameHint` 컬럼은 이름 힌트 공개 여부(T/F)및 힌트 인덱스에 대한 정보를 담고 있지만
`isAnswerHint' 컬럼은 문구 힌트 공개 여부(T/F) 정보만 담고 있어서 네이밍에 차이를 두었습니다.

네이밍이 모호하게 느껴진다면 `isAnswerRevealed`는 어떠신가요

2023-06-29 05:44 UTC, hyeonjeongs commented on src/main/java/com/yello/server/entity/cooldown/Cooldown.java
> +@Table(name= "cooldowns")
앗 entity 생성이 안돼서 네이밍이 sql 예약어중에 혹시나 있나해서 변경했었어요! 저거 지우겠습니다:)

2023-06-29 05:44 UTC, hyeonjeongs commented on src/main/java/com/yello/server/entity/group/School.java
> +    private Long admissionYear;
좋습니다 !

2023-06-29 05:46 UTC, hyeonjeongs commented on src/main/java/com/yello/server/entity/user/User.java
> +    private long point;
아 Ineger로 바꾸는게 좋을 것 같군요 별다른 이유는 없습니다

2023-06-29 05:48 UTC, hyeonjeongs commented on src/main/java/com/yello/server/entity/user/User.java
> +    private long uuid;
넴 알겠습니다~ 일단 String으로 처리하겠습니다

2023-06-29 05:52 UTC, hyeonjeongs commented on src/main/java/com/yello/server/entity/vote/Vote.java
> +    private Boolean inAnswerHint;
엇 이부분은 고민해보겠습니당

2023-06-29 06:58 UTC, devkwonsehoon commented on src/main/java/com/yello/server/entity/user/User.java
> +    private long point;
네 좋슴니다

2023-06-29 06:58 UTC, devkwonsehoon commented on src/main/java/com/yello/server/entity/cooldown/Cooldown.java
> +@Table(name= "cooldowns")
굿 확인 감사합니다~

2023-06-29 07:44 UTC, devkwonsehoon approved these changes
고생하셨습니다

2023-06-29 07:50 UTC, merged